invest: {
  explanation: |md
    ### Invest 
      - expected profit: price
      - loss: target time
      - monitor
        - hist MarketInfo-Strategy performance
        - curr MarketInfo-Strategy performance
  |
}

dashboard: {
  explanation: |md
    ### Index 
      - expected profit: 
      - realized profit: 
      - loss: cost
      - monitor
        - run all the invest.monitor
  |
}
