direction: right
market-info: {
  explanation: |md
    ### TW Market
      - Shioji API (README)
  |
}
stock-filter: {
  explanation: |md
    ### CB Market
      - the Few
  |
}
strategy: {
  explanation: |md
    ### MA 
      - MA 43 -> MA 87
  |
}
report: {
  explanation: |md
    ### Performance
      - MarketInfo-Strategy performance
  |
}

market-info -> stock-filter -> strategy -> report
